package org.magcruise.citywalk;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.Table;

/**
 * クライアントアプリとのJSONインタフェースとなるデータ構造． JSONで受け渡しをするクラスはPOJOでなくてはならない．
 * また，ORMのためのオブジェクトにもなっている．
 *
 * @author nkjm
 *
 */
@Table(name = "ACTIVITIES")
public class Activity {

	public static final String TABLE_NAME = "ACTIVITIES";
	private int id;
	private String userId;
	private String taskId;
	private int score;

	public Activity() {
	}

	public Activity(String userId, String taskId, int score) {
		this.userId = userId;
		this.taskId = taskId;
		this.score = score;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getTaskId() {
		return taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	public int getScore() {
		return score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this,
				ToStringStyle.SHORT_PREFIX_STYLE);
	}

	@Column(autoGenerated = true)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
}
